### ISSUE TITLE
Add Lua integration

### ISSUE THREAD

**Issue by samwilson** [julianhocker/WikidataShow#1]
It'd be nice to be able to access Wikidata data in a wiki's modules, akin to how Wikibase [does it](https://doc.wikimedia.org/Wikibase/master/php/md_docs_topics_lua.html). The most useful method would probably be e.g. `ext.WikidataShow.getEntity( id )` to fetch an entity's entire structure.

**Comment by julianhocker** [comment]
Hi Sam, 
this sounds interesting. However, I do not have any experience with Lua. Can you provide some code to integrate it?
Best,
Julian

**Comment by samwilson** [comment]
Hi! Sorry, I only just saw your reply.

I actually ended up making a new extension for doing this, [UnlinkedWikibase](https://www.mediawiki.org/wiki/Extension:UnlinkedWikibase). I figured the use cases were different enough! :-)
